[package]
name = "t3zktls-prover"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
t3zktls-core = { workspace = true }

tokio = { workspace = true }
serde = { workspace = true }

log = { workspace = true }