[package]
name = "t3zktls-contracts-ethereum"
version.workspace = true
edition.workspace = true

[dependencies]
alloy = { workspace = true, features = ["sol-types", "contract"] }

[build-dependencies]
# t3-zktls-program = { workspace = true, features = ["r0-backend"] }